### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by bresleveloper** [jmaister/excellentexport#393]
All is needed is to have `rtl` as a last param in the `convert` function (and api)
then, after defining `workbook` add

```
        if (rtl && rtl == true) {
            workbook.Workbook = {
                Views : [{RTL : true}]
            }
        }
```

**Comment by jmaister** [comment]
Thanks @bresleveloper

Could you share any example of RTL table to check if it works properly?

**Comment by bresleveloper** [comment]
technically I just wrote in hebrew, but you can change the direction of the worksheet via  Layout -> Sheet RTL
![image](https://user-images.githubusercontent.com/2042279/105754984-5e108f80-5f53-11eb-8a5b-3efb8152a45f.png)

**Comment by jmaister** [comment]
Should the RTL be defined at workbook level or independently on each sheet?

**Comment by jmaister** [comment]
I created a PR with the RTL support: #416 
It works in OpenOffice Calc. I haven't tried in Microsoft Excel.

Does it work for you?

**Comment by Qusay779** [comment]
Hey, is there a reason for not merging that pr?

i need rtl, where everything starts from the right, and not only for text alignment.

if merging is not an option, what should i do if I'm still relying on Excelentexport

**Comment by jmaister** [comment]
Hi @Qusay779, what I need is a table for testing and check that the RLT works.

If you provide an HTML table would be very helpful, so I can share the resulting Excel with you to confirm that it has the right content.

**Comment by Qusay779** [comment]
Thanks for the reply, same as OP i need rtl because even if my text is English and not something like Arabic/Hebrew i would still want them to switch.

[rtl going ltr from file](
https://gyazo.com/87c79ab8892f1132fdb9c07195faa609)
[rtl being rtl in my project](https://gyazo.com/65602605331123343f7f520a820e4c48)

I'm not sure if this is enough or correct.. but here is the one i used in the pics.

```
<table>
 <thead>
    <tr>
      <th>االلغة</th>
      <th>عدد الأحرف</th>
      <th>Country</th>
      <th>miص-ص</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>العربية</td>
      <td>٢٨</td>
      <td>Earth</td>
      <td>ن0ن</td>
    </tr>
    <tr>
      <td>العبرية</td>
      <td>٢٢</td>
      <td>Isreal</td>
      <td>ضSض</td>
    </tr>
  </tbody>
</table>
```

**Comment by jmaister** [comment]
This is the result in an Excel file.
Does it make sense?

![image](https://user-images.githubusercontent.com/374021/151230534-8d8a7d58-dc69-4aec-9f95-66ca72e7bc17.png)

**Comment by Qusay779** [comment]
Thanks for the update, i hope that I'm not expecting something beyond doable, but what I'm looking for is having columns switch like ABCD to start from the right ...DCBA

this is an XLSX file that has that, it starts from right with no config to readers on any of my devices.

[נוכחות.xlsx](https://github.com/jmaister/excellentexport/files/7945558/default.xlsx)

**Comment by Qusay779** [comment]
characters are fine, the columns are switched. or should i say the entire layout?

and I'm not using a table for generating my files, I'm using their data through sheet config from.array , giving the id of my tables produces files where values are wrapped with their html, also they are RTL , in the file they are not.

[my project table](https://gyazo.com/b99f35b8971c75050e4f066533c81d4e)

[table output](https://gyazo.com/c1475dfaac9cc988c9bb651b8c4d2f05)

and the table i attached here is already RTL like the other tables in my project. its just that the file shows the columns in reverse.

[my config of latest ts pr fork](https://gyazo.com/34e10fa4e8a8dc037284993ab64739cb) table id passed for testing.

[array output](https://gyazo.com/0361e51b99cca7427a6b08f32839a379)

i know my tables are not pure, i also need to be able to give color to the headers and if that's only possible with a table, ill make a custom one since sheet config can take an element for table, but shouldn't I be able to switch ? even without a table?

the XLSX file attached in my last reply is a perfect example for the outcome Im looking for.

[screen shot of my attached file](https://gyazo.com/fa7b200f7e2a5c0826be45ecb4e2decd)

so my request is to be able to have layout changed when passing RTL option, headers to have color, or be able to customize the way cells appear in excel, output from my testing for table id to my tables doesn't show the color applied

[what i mean by color](https://gyazo.com/6c3e0068337159d4e2dac5998de9cece) both css and inline

Thanks for your effort.
